### ISSUE TITLE
Facet version selection seems to go wrong.

### ISSUE THREAD

**Issue by LukeP0WERS** [mkeeter/fidget#313]
When compiling fidget I get the error: ``cannot find type `Wip` in crate `facet` `` in several places in `fidget-0.3.7\src\rhai\shapes.rs`. I think the automatic version selection is selecting a different version for me than it is for you. Not sure what would cause that, I am using the nightly toolchain if that would affect things, and the facet version my system is using is `0.27.10`.

**Comment by LukeP0WERS** [comment]
Figured out facet needs the following crates to be pinned for fidget to work properly: 
```toml
facet = { version = "=0.27.1" }
facet-derive-emit = { version = "=0.27.1" }
facet-derive-parse = { version = "=0.27.1" }
facet-core = { version = "=0.27.1" }
```
